= GitFlow Version Plugin
:latestRevision: 1.0.2
:toc:
:icons: font

NOTE: This plugins requires Gradle 6.

== Summary
This plugin calculates the version from the Git repository. The plugin assumes that the used workflow follows the GitFlow principle. See https://infos.seibert-media.net/display/Productivity/Git-Workflows+-+Der+Gitflow-Workflow (DE) or https://datasift.github.io/gitflow/IntroducingGitFlow.html (EN).

image::images/gitflow_example.svg[]

The version depends on the local repository and the current active branch and the tag. Furthermore, the plugin checks the local sources if there are uncommitted changes in the source repository.

With the task `showVersion` it is possible to check the current version. Please switch to the info log level if you need more information about the calculation.

== Plugin Extension "gitflowVersion"

It is possible to configure the separator, prefixes and branch names and type of version. With one Gradle property it is possible to change the
version to "local".

=== Properties
[cols="20%,15%,15%,50%", width="95%", options="header"]
|===
|Property           | Type   | Default value | Description
|*defaultVersion*   | String | 1.0.0         | This is the default version if no other information is available.
|*mainBranch*       | String | master        | Name of the main branch, used for releae version
|*developBranch*    | String | develop       | Name of the developer branch, used for integration
|*hotfixPrefix*     | String | hotfix        | Prefix for hotfix branches, used for bug fix development
|*featurePrefix*    | String | feature       | Prefix for feature branches, used for feature development
|*releasePrefix*    | String | release       | Prefix for release branches, used for release preparation
|*versionPrefix*    | String | version       | Prefix for version tags
|*separator*        | String | /             | Separator for branches and tags
|*versionType*      | String | three         | Type of the version - *three* digits or *four* digits version number Possible values are `three` or `four`.
|*versionService*   | String | (read only)   | The service for version calculation.
|*version*          | String | (read only)   | This is the calculated version.
|*previousVersion*  | String | (read only)   | This is the calculated previous version on the branch.
|*branchName*       | String | (read only)   | This is the current branch name.
|===

If the Gradle property "localVersion" is true, the version is always "local".

++++
<details open>
<summary>Groovy</summary>
++++
.build.gradle
[source,groovy]
----
plugins {
    id 'com.intershop.gradle.version.gitflow' version '{latestRevision}'
}

gitflowVersion {
    versionType = "three"

    defaultVersion = "2.0.0"
    mainBranch = "master"
    developBranch = "develop"
    hotfixPrefix = "hotfix"
    featurePrefix = "feature"
    releasePrefix = "release"
}

version = gitflowVersion.version
----
++++
</details>
++++

++++
<details>
<summary>Kotlin</summary>
++++
.build.gradle.kts
[source,kotlin]
----
plugins {
    id("com.intershop.gradle.version.gitflow") version "{latestRevision}"
}

gitflowVersion {
    versionType = "three"

    defaultVersion = "2.0.0"
    mainBranch = "master"
    developBranch = "develop"
    hotfixPrefix = "hotfix"
    featurePrefix = "feature"
    releasePrefix = "release"
}

version = gitflowVersion.version
----
++++
</details>
++++

=== Version Calculation - Summary
* Main Branch (master) +
The plugin is looking for a tag on the branch with the version prefix. If there is no tag the default value is used and extended with `SNAPSHOT`. If the current commit is without a tag, the first founded tag is used for the calculation and also extended `SNAPSHOT`. When the current commit has a tag with the version extension the version is used from the tag name.

* Developer Branch (develop)
The version is always 'dev-SNAPSHOT'. No other version information is possible on the branch.

* Feature / Hotfix Branch (feature / hotfix)
The version is always the branch name (words connected with hyphens) and extended with SNAPSHOT.
Example: branch name is feature/branch-name -> 'branch-name-SNAPSHOT'

* Release branches (release)
The version is calculated from the branch name and extended with SNAPSHOT.
Example: release/7.11 -> '7.11.0.0-SNAPSHOT' (Version type is 'four')

== Tasks

[cols="20%,15%,65%", width="95%", options="header"]
|===
|Task name  |Type             |Description

| showVersion    | ShowVersion    | Shows the current version and the previous version of the current working copy.
| createChangLog | CreateChangLog | Creates a changelog for the current working copy, starting with the previous version or with the first commit, if there is no previous version.
|===

== License

Copyright 2014-2020 Intershop Communications.

Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
